### ISSUE TITLE
Universal build failing

### ISSUE THREAD

**Issue by freezy** [czeckd/angular-svg-icon#62]
When compiling for server-side, I'm getting the following error:

```
ReferenceError: document is not defined
    at MapSubscriber.project (node_modules/angular-svg-icon/bundles/angular-svg-icon.umd.js:80:31)
    at MapSubscriber._next (node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (node_modules/rxjs/internal/Subscriber.js:67:18)
    at MapSubscriber._next (node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (node_modules/rxjs/internal/Subscriber.js:67:18)
    at FilterSubscriber._next (node_modules/rxjs/internal/operators/filter.js:52:30)
    at FilterSubscriber.Subscriber.next (node_modules/rxjs/internal/Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (node_modules/rxjs/internal/Subscriber.js:67:18)
```

Running with latest Angular (7.2.0), but I haven't tested other versions. Looks like a classic Universal bug, since `document` is not available when rendering server-side?

**Comment by freezy** [comment]
Looks like [this](https://github.com/czeckd/angular-svg-icon/blob/master/lib/src/svg-icon-registry.service.ts#L54) is the problem, it should be `this.document`. However what I don't understand is why it's there, given that line was commited [Nov 9](https://github.com/czeckd/angular-svg-icon/blame/master/lib/src/svg-icon-registry.service.ts#L54), and the Universal PR which does it [correctly](https://github.com/czeckd/angular-svg-icon/pull/57/files#diff-181045d7b93914b7687ae3b2506dd0acR50) went upstream on Nov 24.

**Comment by czeckd** [comment]
@freezy Yes, you're right. I'll get it fixed.

**Comment by czeckd** [comment]
@freezy angular-svg-icon@7.0.2 published to npm. Please let me know if it doesn't resolve the defect you found. Thanks for you help finding it and tracking it down.

**Comment by freezy** [comment]
You're the best! Thanks! :)
